title: Standard for Public Code
version: 0.1.0

remote_theme: publiccodenet/jekyll-theme
include: 
  - "README.md"
  - "CONTRIBUTING.md"
  - "LICENCE.md"

toc: true

defaults:
  -
    scope:
      path: '/criteria/[!index]*'
    values:
      breadcrumbs:
        - name: 'Criteria'
          path: '/criteria/'
  -
    scope: 
      path: '/'
    values:
      breadcrumbs: true
