name: Test
on:
  push:
    branches:
      - ghactions-test-202101

defaults:
  run:
    shell: bash
    # working-directory: scripts

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle install
      - run: ./script/cibuild.sh
